"""
Django settings for AuroraClient project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _aurora_secret_key() -> str:
    """Per-install key. A key baked into the installer would be extractable."""
    env_key = os.environ.get("AURORA_SECRET_KEY", "").strip()
    if env_key:
        return env_key
    key_path = Path.home() / ".aurora" / "secret_key"
    if key_path.is_file():
        stored = key_path.read_text(encoding="utf-8").strip()
        if stored:
            return stored
    from django.core.management.utils import get_random_secret_key
    generated = get_random_secret_key()
    try:
        key_path.parent.mkdir(parents=True, exist_ok=True)
        key_path.write_text(generated + "\n", encoding="utf-8")
        os.chmod(key_path, 0o600)
    except OSError:
        pass
    return generated


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _aurora_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Configure CORS to allow specific origins
CORS_ALLOWED_ORIGINS = [
    "https://hallgrimssonlab.ca",
    "http://0.0.0.0:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://0.0.0.0:8001",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
    "http://0.0.0.0:8002",
    "http://localhost:8002",
    "http://127.0.0.1:8002",
    "http://0.0.0.0:8003",
    "http://localhost:8003",
    "http://127.0.0.1:8003",
    "http://0.0.0.0:8004",
    "http://localhost:8004",
    "http://127.0.0.1:8004"
]

# Remote frontend (hallgrimssonlab.ca / dev server) → local Aurora (127.0.0.1:8020)
CORS_ALLOW_PRIVATE_NETWORK = True

# If you need to allow both HTTP and HTTPS versions, you can add both:
# CORS_ALLOWED_ORIGINS = [
#     "https://hallgrimssonlab.ca",
#     "http://hallgrimssonlab.ca",
# ]

# Remove or comment out the following line since we're now using CORS_ALLOWED_ORIGINS
# CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'pipeline'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AuroraClient.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AuroraClient.wsgi.application'

ASGI_APPLICATION = 'AuroraClient.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# Local Aurora does not store users, scans, or project data here — those live on
# BHTools and the filesystem. Django still needs sqlite for its own tables
# (sessions / contenttypes / admin). Keep that file in a user-writable data dir
# so packaged Linux (/opt, root-owned) and future Django models both work.


_PACKAGED_LINUX_ROOT = Path("/opt/aurora-tools")


def _ensure_dir(path: Path) -> Path:
    try:
        path.mkdir(parents=True, exist_ok=True)
    except OSError:
        pass
    return path


def _aurora_data_dir() -> Path:
    env_dir = os.environ.get("AURORA_DATA_DIR", "").strip()
    if env_dir:
        return _ensure_dir(Path(env_dir))
    if _PACKAGED_LINUX_ROOT in BASE_DIR.parents or BASE_DIR.parent == _PACKAGED_LINUX_ROOT:
        return _ensure_dir(Path.home() / ".aurora")
    if os.access(BASE_DIR, os.W_OK):
        return BASE_DIR
    return _ensure_dir(Path.home() / ".aurora")


def _aurora_sqlite_path() -> Path:
    env_path = os.environ.get("AURORA_SQLITE_PATH", "").strip()
    if env_path:
        chosen = Path(env_path)
        _ensure_dir(chosen.parent)
        return chosen

    chosen = _aurora_data_dir() / "db.sqlite3"
    packaged = BASE_DIR / "db.sqlite3"
    if chosen != packaged and packaged.exists() and not chosen.exists():
        try:
            import shutil
            shutil.copy2(packaged, chosen)
        except OSError:
            pass
    return chosen


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _aurora_sqlite_path(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Upload size limits for mask data
# Allow masks up to ~1 GB (full-res 1024^3 bytes). Adjust to your worst case.
DATA_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024 * 1024
# Don't complain about single-form-field size
DATA_UPLOAD_MAX_NUMBER_FIELDS = None
